title: Linjie Zhang
name: Linjie Zhang
description: Robotics | Control | AI Systems
url: "https://linjiez-png.github.io"

remote_theme: "mmistakes/minimal-mistakes@4.28.0"

plugins:
  - jekyll-include-cache

author:
  name: "Linjie Zhang"
  avatar: "/assets/images/profile.png"
  bio: "Mechanical Engineer | Robotics, Control, and AI"
  location: "Carnegie Mellon University"

nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "Resume"
    url: /resume/
